#! /bin/sh

echo "HHHHHHH"

# BIB=`pwd`/bib/all.bib

cat - | /usr/local/bin/pandoc --crossref --citeproc -f markdown -t html -N --metadata link-citations=true --bibliography=bib/all.bib --csl=bib/ieee-with-url.csl
